-- ============================================================
-- Gaspol — evolve the single-user fit_* prototype to multi-user
-- (PRD F10). Adds user_id + per-user RLS, the upsert constraints the
-- data layer relies on, progress-photo storage, and a premium flag.
--
-- SAFETY: this is written for the SHARED project ticdiatbdxkmpzmqvntn,
-- which also hosts "No Bites Left". It ONLY touches fit_* tables — never
-- run anything here against non-fit_ tables.
--
-- The prototype currently has OPEN ANON policies (single user). This
-- migration tightens them. Before enforcing, backfill existing rows with
-- your own auth uid, e.g.:
--   update fit_set_logs   set user_id = '<your-uid>' where user_id is null;
--   (repeat for each fit_ table)
-- Apply locally first: `supabase db reset` / `supabase migration up`.
-- ============================================================

-- 1) user_id columns -----------------------------------------------------
alter table fit_exercises     add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table fit_set_logs      add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table fit_foods         add column if not exists user_id uuid references auth.users(id) on delete cascade; -- null = shared library
alter table fit_food_logs     add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table fit_body_metrics  add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table fit_checkins      add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table fit_settings      add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table fit_coach_notes   add column if not exists user_id uuid references auth.users(id) on delete cascade;

-- 2) constraints the data layer upserts against --------------------------
create unique index if not exists fit_body_metrics_user_date on fit_body_metrics (user_id, log_date);
create unique index if not exists fit_checkins_user_date     on fit_checkins (user_id, log_date);
create unique index if not exists fit_settings_user_key      on fit_settings (user_id, key);
create index if not exists fit_set_logs_user_date  on fit_set_logs (user_id, log_date);
create index if not exists fit_food_logs_user_date on fit_food_logs (user_id, log_date);
create index if not exists fit_exercises_user_day  on fit_exercises (user_id, day_of_week) where active;

-- 3) default user_id = the caller on insert ------------------------------
alter table fit_set_logs     alter column user_id set default auth.uid();
alter table fit_food_logs    alter column user_id set default auth.uid();
alter table fit_body_metrics alter column user_id set default auth.uid();
alter table fit_checkins     alter column user_id set default auth.uid();

-- 4) Row-Level Security --------------------------------------------------
-- Replace the prototype's open policies with per-user ones. Owner = user_id.
do $$
declare t text;
begin
  foreach t in array array[
    'fit_exercises','fit_set_logs','fit_food_logs','fit_body_metrics',
    'fit_checkins','fit_settings','fit_coach_notes'
  ] loop
    execute format('alter table %I enable row level security', t);
    -- drop any prototype policies (names vary; drop-if-exists the common ones)
    execute format('drop policy if exists "anon all" on %I', t);
    execute format('drop policy if exists "public" on %I', t);
    execute format('drop policy if exists %I on %I', t || '_owner', t);
    execute format($f$
      create policy %I on %I
        for all
        using (user_id = auth.uid())
        with check (user_id = auth.uid())
    $f$, t || '_owner', t);
  end loop;
end $$;

-- fit_foods: shared library (user_id null) is readable by everyone; users
-- may add/edit only their own custom foods.
alter table fit_foods enable row level security;
drop policy if exists "anon all" on fit_foods;
drop policy if exists fit_foods_read on fit_foods;
drop policy if exists fit_foods_write on fit_foods;
create policy fit_foods_read  on fit_foods for select using (user_id is null or user_id = auth.uid());
create policy fit_foods_write on fit_foods for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- 5) Premium flag lives in fit_settings.profile.value->>'premium' --------
--    (no schema change; documented for the food-photo gate.)

-- 5b) Weekly review payload: structured stats + changelog for the app's
--     Progress screen (title/body hold the human-tone note).
alter table fit_coach_notes add column if not exists data jsonb not null default '{}'::jsonb;

-- 6) Progress photos (F6) — metadata + private storage -------------------
create table if not exists fit_photos (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  taken_on    date not null default ((now() at time zone 'Asia/Jakarta')::date),
  pose        text not null default 'front',   -- front | side | back
  storage_path text not null,                  -- object path in the 'fit-photos' bucket
  created_at  timestamptz not null default now()
);
alter table fit_photos enable row level security;
create policy fit_photos_owner on fit_photos for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Private storage bucket for the actual image files.
insert into storage.buckets (id, name, public)
values ('fit-photos', 'fit-photos', false)
on conflict (id) do nothing;

-- Users may only touch objects under their own uid/ prefix.
create policy "fit-photos read own"   on storage.objects for select
  using (bucket_id = 'fit-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "fit-photos write own"  on storage.objects for insert
  with check (bucket_id = 'fit-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "fit-photos delete own" on storage.objects for delete
  using (bucket_id = 'fit-photos' and (storage.foldername(name))[1] = auth.uid()::text);

-- ============================================================
-- After applying: keep the weekly-coach-review job compatible with this
-- schema (it now reads/writes user-scoped rows). See supabase/schedules.sql.
-- ============================================================
