-- ============================================================
-- Gaspol — additive, NON-BREAKING multi-user prep for fit_*
-- STATUS: ALREADY APPLIED to the shared project ticdiatbdxkmpzmqvntn
--         (via MCP apply_migration "fit_multiuser_additive"). Safe to
--         re-run — every statement is guarded with IF NOT EXISTS / ON CONFLICT.
--
-- Touches ONLY fit_* tables + a new private "fit-photos" storage bucket.
-- The existing open "fit anon all" policies are intentionally LEFT IN PLACE so
-- the single-user prototype keeps working. Per-user RLS enforcement lives in
-- the companion migration 20260716120100_fit_rls_enforce.sql (run AFTER auth
-- + backfilling user_id).
-- ============================================================

-- 1) user_id columns (nullable — existing rows stay visible under open policy)
alter table fit_exercises    add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table fit_set_logs     add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table fit_foods        add column if not exists user_id uuid references auth.users(id) on delete cascade; -- null = shared library
alter table fit_food_logs    add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table fit_body_metrics add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table fit_checkins     add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table fit_settings     add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table fit_coach_notes  add column if not exists user_id uuid references auth.users(id) on delete cascade;

-- 2) default user_id = caller on insert (harmless for anon: resolves to null)
alter table fit_set_logs     alter column user_id set default auth.uid();
alter table fit_food_logs    alter column user_id set default auth.uid();
alter table fit_body_metrics alter column user_id set default auth.uid();
alter table fit_checkins     alter column user_id set default auth.uid();

-- 3) upsert constraints the data layer relies on
create unique index if not exists fit_body_metrics_user_date on fit_body_metrics (user_id, log_date);
create unique index if not exists fit_checkins_user_date     on fit_checkins (user_id, log_date);
create unique index if not exists fit_settings_user_key      on fit_settings (user_id, key);
create index if not exists fit_set_logs_user_date  on fit_set_logs (user_id, log_date);
create index if not exists fit_food_logs_user_date on fit_food_logs (user_id, log_date);
create index if not exists fit_exercises_user_day  on fit_exercises (user_id, day_of_week) where active;

-- 4) F8 weekly-review structured payload (stats + changelog next to the note)
alter table fit_coach_notes add column if not exists data jsonb not null default '{}'::jsonb;

-- 5) Progress photos (F6): new, isolated table with its own owner RLS
create table if not exists fit_photos (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  taken_on     date not null default ((now() at time zone 'Asia/Jakarta')::date),
  pose         text not null default 'front',   -- front | side | back
  storage_path text not null,                   -- object path in the 'fit-photos' bucket
  created_at   timestamptz not null default now()
);
alter table fit_photos enable row level security;
drop policy if exists fit_photos_owner on fit_photos;
create policy fit_photos_owner on fit_photos for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- 6) private storage bucket + per-user object policies (folder prefix = uid)
insert into storage.buckets (id, name, public) values ('fit-photos','fit-photos',false) on conflict (id) do nothing;
drop policy if exists "fit-photos read own"   on storage.objects;
drop policy if exists "fit-photos write own"  on storage.objects;
drop policy if exists "fit-photos delete own" on storage.objects;
create policy "fit-photos read own"   on storage.objects for select using (bucket_id='fit-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "fit-photos write own"  on storage.objects for insert with check (bucket_id='fit-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "fit-photos delete own" on storage.objects for delete using (bucket_id='fit-photos' and (storage.foldername(name))[1] = auth.uid()::text);
