-- ============================================================
-- Gaspol — full base schema for the fit_* tables.
--
-- This is the consolidated, version-controlled schema for the dedicated
-- "gaspol" Supabase project (kxhalnjrcayzsbclfeaz). It folds together what
-- were previously the (un-tracked) base tables + the additive multi-user
-- migration, so a fresh project can be stood up from git alone.
--
-- Prototype posture: RLS is ON but every fit_* table (except fit_photos)
-- carries an open "fit anon all" policy so the app works with the anon key
-- before auth is enabled. Per-user enforcement lives in the companion
-- 20260716120100_fit_rls_enforce.sql (run AFTER auth is on).
-- ============================================================

-- ---- Tables -------------------------------------------------
create table if not exists public.fit_exercises (
  id             integer generated by default as identity primary key,
  session        text    not null,
  day_of_week    integer not null,
  sort_order     integer not null,
  name           text    not null,
  target_sets    integer not null,
  rep_low        integer not null,
  rep_high       integer not null,
  current_weight numeric,
  increment      numeric not null default 1,
  is_compound    boolean not null default false,
  rest_sec       integer default 90,
  notes          text,
  active         boolean not null default true,
  user_id        uuid references auth.users(id) on delete cascade
);

create table if not exists public.fit_set_logs (
  id          bigint  generated by default as identity primary key,
  log_date    date    not null default ((now() at time zone 'Asia/Jakarta')::date),
  exercise_id integer not null references public.fit_exercises(id),
  set_number  integer not null,
  weight      numeric,
  reps        integer not null,
  rpe         numeric,
  created_at  timestamptz not null default now(),
  user_id     uuid default auth.uid() references auth.users(id) on delete cascade
);

create table if not exists public.fit_foods (
  id         integer generated by default as identity primary key,
  name       text    not null,
  serving    text,
  kcal       numeric not null,
  protein    numeric not null default 0,
  carbs      numeric not null default 0,
  fat        numeric not null default 0,
  sort_order integer default 100,
  user_id    uuid references auth.users(id) on delete cascade  -- null = shared library
);

create table if not exists public.fit_food_logs (
  id         bigint  generated by default as identity primary key,
  log_date   date    not null default ((now() at time zone 'Asia/Jakarta')::date),
  meal       text,
  name       text    not null,
  qty        numeric not null default 1,
  kcal       numeric not null,
  protein    numeric not null default 0,
  carbs      numeric not null default 0,
  fat        numeric not null default 0,
  created_at timestamptz not null default now(),
  user_id    uuid default auth.uid() references auth.users(id) on delete cascade
);

create table if not exists public.fit_body_metrics (
  id                integer generated by default as identity primary key,
  log_date          date not null default ((now() at time zone 'Asia/Jakarta')::date),
  weight_kg         numeric,
  bf_pct            numeric,
  muscle_kg         numeric,
  waist_cm          numeric,
  hip_cm            numeric,
  chest_cm          numeric,
  notes             text,
  created_at        timestamptz not null default now(),
  lean_body_mass_kg numeric,
  neck_cm           numeric,
  shoulder_cm       numeric,
  abdomen_cm        numeric,
  biceps_l_cm       numeric,
  biceps_r_cm       numeric,
  forearm_l_cm      numeric,
  forearm_r_cm      numeric,
  thigh_l_cm        numeric,
  thigh_r_cm        numeric,
  calf_l_cm         numeric,
  calf_r_cm         numeric,
  bmr_kcal          numeric,
  visceral_fat      numeric,
  bmi               numeric,
  whr               numeric,
  source            text,
  scan              jsonb,
  user_id           uuid default auth.uid() references auth.users(id) on delete cascade
);

create table if not exists public.fit_checkins (
  id            integer generated by default as identity primary key,
  log_date      date not null default ((now() at time zone 'Asia/Jakarta')::date),
  sleep_hours   numeric,
  sleep_quality integer,
  energy        integer,
  soreness      integer,
  notes         text,
  created_at    timestamptz not null default now(),
  user_id       uuid default auth.uid() references auth.users(id) on delete cascade
);

create table if not exists public.fit_settings (
  key     text primary key,
  value   jsonb not null,
  user_id uuid references auth.users(id) on delete cascade
);

create table if not exists public.fit_coach_notes (
  id         integer generated by default as identity primary key,
  note_date  date not null default ((now() at time zone 'Asia/Jakarta')::date),
  title      text not null,
  body       text not null,
  created_at timestamptz not null default now(),
  user_id    uuid references auth.users(id) on delete cascade,
  data       jsonb not null default '{}'::jsonb
);

create table if not exists public.fit_photos (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  taken_on     date not null default ((now() at time zone 'Asia/Jakarta')::date),
  pose         text not null default 'front',   -- front | side | back
  storage_path text not null,
  created_at   timestamptz not null default now()
);

-- ---- Indexes (upsert targets + query paths) -----------------
create unique index if not exists fit_body_metrics_user_date on public.fit_body_metrics (user_id, log_date);
create unique index if not exists fit_checkins_user_date     on public.fit_checkins (user_id, log_date);
create unique index if not exists fit_settings_user_key      on public.fit_settings (user_id, key);
create index        if not exists fit_set_logs_user_date     on public.fit_set_logs (user_id, log_date);
create index        if not exists fit_food_logs_user_date    on public.fit_food_logs (user_id, log_date);
create index        if not exists fit_exercises_user_day     on public.fit_exercises (user_id, day_of_week) where active;

-- ---- RLS: prototype open policies (anon) --------------------
do $$
declare t text;
begin
  foreach t in array array[
    'fit_exercises','fit_set_logs','fit_foods','fit_food_logs',
    'fit_body_metrics','fit_checkins','fit_settings','fit_coach_notes'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "fit anon all" on public.%I', t);
    execute format('create policy "fit anon all" on public.%I for all to anon using (true) with check (true)', t);
  end loop;
end $$;

-- fit_photos: owner-only from day one (feature isolated).
alter table public.fit_photos enable row level security;
drop policy if exists fit_photos_owner on public.fit_photos;
create policy fit_photos_owner on public.fit_photos for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---- Private storage bucket for progress photos (F6) --------
insert into storage.buckets (id, name, public) values ('fit-photos','fit-photos',false) on conflict (id) do nothing;
drop policy if exists "fit-photos read own"   on storage.objects;
drop policy if exists "fit-photos write own"  on storage.objects;
drop policy if exists "fit-photos delete own" on storage.objects;
create policy "fit-photos read own"   on storage.objects for select using (bucket_id='fit-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "fit-photos write own"  on storage.objects for insert with check (bucket_id='fit-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "fit-photos delete own" on storage.objects for delete using (bucket_id='fit-photos' and (storage.foldername(name))[1] = auth.uid()::text);

-- ---- Grants (RLS still governs row visibility) --------------
grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
